# Generated by Django 5.0.4 on 2024-04-08 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0002_genre_material_painting"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country_name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "countries",
                "ordering": ("country_name",),
            },
        ),
        migrations.AlterField(
            model_name="city",
            name="country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="countries",
                to="gallery.country",
            ),
        ),
    ]
