# Generated by Django 5.0.4 on 2024-04-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0004_alter_artist_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="painting",
            name="image_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
