# Generated by Django 5.0.4 on 2024-04-09 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0005_alter_painting_image_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Style",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("style_name", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ("style_name",),
            },
        ),
        migrations.AddField(
            model_name="painting",
            name="style",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="styles",
                to="gallery.style",
            ),
        ),
    ]
