# Generated by Django 5.0.4 on 2024-04-10 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0006_style_painting_style"),
    ]

    operations = [
        migrations.AlterField(
            model_name="painting",
            name="artist",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="paintings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
