# Generated by Django 5.0.4 on 2024-04-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0007_alter_painting_artist"),
    ]

    operations = [
        migrations.AddField(
            model_name="painting",
            name="small_image_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
